DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS chords CASCADE;
DROP TABLE IF EXISTS song_chords CASCADE;
DROP TABLE IF EXISTS user_songs CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE songs (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL
);

CREATE TABLE chords (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(5) NOT NULL
);

CREATE TABLE song_chords (
  id SERIAL PRIMARY KEY NOT NULL,
  song_id INTEGER REFERENCES songs(id) ON DELETE CASCADE,
  chord_id INTEGER REFERENCES chords(id) ON DELETE CASCADE
);

CREATE TABLE user_songs (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  song_id INTEGER REFERENCES songs(id) ON DELETE CASCADE
);